package Server.PlayerSide.PlayerInterfacePackage;


/**
* Server/PlayerSide/PlayerInterfacePackage/StringArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from playerinterface.idl
* Friday, May 30, 2025 1:40:42 PM SGT
*/

public final class StringArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringArrayHolder ()
  {
  }

  public StringArrayHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.PlayerSide.PlayerInterfacePackage.StringArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.PlayerSide.PlayerInterfacePackage.StringArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.PlayerSide.PlayerInterfacePackage.StringArrayHelper.type ();
  }

}
