package Server.AdminSide;


/**
* Server/AdminSide/AdminInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admininterface.idl
* Friday, May 30, 2025 8:51:05 PM SGT
*/

public interface AdminInterfaceOperations 
{
  void createPlayer (String playerId, String password) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  void editUserDetails (String userId, String password) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NoSuchUserFoundException;
  void deleteUser (String userId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NoSuchUserFoundException;
  Server.CommonObjects.User[] getUserList () throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  Server.CommonObjects.User searchUser (String playerId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NoSuchUserFoundException;
  Server.CommonObjects.GameRules changeRules (int waitingDuration, int gameDuration) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  Server.CommonObjects.GameResult[] getGameHistory () throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  Server.CommonObjects.GameResult[] getPlayerHistory (String playerId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NoSuchUserFoundException;
  String ping (String userId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
} // interface AdminInterfaceOperations
