package Server.AdminSide;

/**
* Server/AdminSide/AdminInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminInterface.idl
* Wednesday, May 28, 2025 12:20:18 AM AWST
*/

public final class AdminInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminInterface value = null;

  public AdminInterfaceHolder ()
  {
  }

  public AdminInterfaceHolder (AdminInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminInterfaceHelper.type ();
  }

}
