package Server.AdminSide;


/**
* Server/AdminSide/AdminInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminInterface.idl
* Wednesday, May 28, 2025 12:20:18 AM AWST
*/

public interface AdminInterfaceOperations 
{
  Server.CommonObjects.User login (Server.CommonInterface.CallBackInterface cb, String userId, String password) throws Server.Exceptions.LostConnectionException, Server.Exceptions.AlreadyLoggedInException;
  void createPlayer (String playerId, String password) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  void editUserDetails (String userId, String password) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NoSuchUserFoundException;
  void deleteUser (String userId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NoSuchUserFoundException;
  Server.CommonObjects.User[] getUserList () throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  Server.CommonObjects.User searchUser (String playerId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NoSuchUserFoundException;
  Server.CommonObjects.GameRules changeRules (int waitingDuration, int gameDuration) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  Server.CommonObjects.GameResult[] getGameHistory () throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  Server.CommonObjects.GameResult[] getPlayerHistory (String playerId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NoSuchUserFoundException;
  String ping (String userId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
} // interface AdminInterfaceOperations
