package Server.AdminSide;


/**
* Server/AdminSide/AdminInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminInterface.idl
* Wednesday, May 28, 2025 12:20:18 AM AWST
*/

public interface AdminInterface extends AdminInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminInterface
