package Server.AdminSide;


/**
* Server/AdminSide/AdminInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admininterface.idl
* Friday, May 30, 2025 8:51:05 PM SGT
*/

public interface AdminInterface extends AdminInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminInterface
