package Server.AdminSide;

/**
* Server/AdminSide/GameResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admininterface.idl
* Friday, May 30, 2025 8:51:05 PM SGT
*/

public final class GameResultHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.AdminSide.GameResult value = null;

  public GameResultHolder ()
  {
  }

  public GameResultHolder (Server.AdminSide.GameResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.AdminSide.GameResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.AdminSide.GameResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.AdminSide.GameResultHelper.type ();
  }

}
