package Server.AdminSide;


/**
* Server/AdminSide/GameResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admininterface.idl
* Friday, May 30, 2025 6:42:56 PM SGT
*/

public final class GameResult implements org.omg.CORBA.portable.IDLEntity
{
  public String sessionId = null;
  public String winner = null;
  public int roundsPlayed = (int)0;
  public int totalGuessesMade = (int)0;
  public int duration = (int)0;

  public GameResult ()
  {
  } // ctor

  public GameResult (String _sessionId, String _winner, int _roundsPlayed, int _totalGuessesMade, int _duration)
  {
    sessionId = _sessionId;
    winner = _winner;
    roundsPlayed = _roundsPlayed;
    totalGuessesMade = _totalGuessesMade;
    duration = _duration;
  } // ctor

} // class GameResult
