package Server.AdminSide;

/**
* Server/AdminSide/LobbyInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admininterface.idl
* Friday, May 30, 2025 6:42:56 PM SGT
*/

public final class LobbyInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.AdminSide.LobbyInfo value = null;

  public LobbyInfoHolder ()
  {
  }

  public LobbyInfoHolder (Server.AdminSide.LobbyInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.AdminSide.LobbyInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.AdminSide.LobbyInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.AdminSide.LobbyInfoHelper.type ();
  }

}
