package Server.AdminSide;


/**
* Server/AdminSide/usersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminInterface.idl
* Wednesday, May 28, 2025 12:20:18 AM AWST
*/

public final class usersHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.CommonObjects.User value[] = null;

  public usersHolder ()
  {
  }

  public usersHolder (Server.CommonObjects.User[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = usersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    usersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return usersHelper.type ();
  }

}
