package Server.PlayerSide;


/**
* Server/PlayerSide/GameHistoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from playerinterface.idl
* Friday, May 30, 2025 4:23:52 PM SGT
*/

public final class GameHistoryHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.CommonObjects.GameResult value[] = null;

  public GameHistoryHolder ()
  {
  }

  public GameHistoryHolder (Server.CommonObjects.GameResult[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.PlayerSide.GameHistoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.PlayerSide.GameHistoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.PlayerSide.GameHistoryHelper.type ();
  }

}
