package Server.PlayerSide;


/**
* Server/PlayerSide/LobbyListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from playerinterface.idl
* Friday, May 30, 2025 1:40:42 PM SGT
*/

public final class LobbyListHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.CommonObjects.LobbyInfo value[] = null;

  public LobbyListHolder ()
  {
  }

  public LobbyListHolder (Server.CommonObjects.LobbyInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.PlayerSide.LobbyListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.PlayerSide.LobbyListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.PlayerSide.LobbyListHelper.type ();
  }

}
