package Server.PlayerSide;


/**
* Server/PlayerSide/PlayerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from playerinterface.idl
* Saturday, May 31, 2025 1:32:22 PM SGT
*/

public interface PlayerInterface extends PlayerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerInterface
