package Server.PlayerSide;


/**
* Server/PlayerSide/PlayerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from playerinterface.idl
* Saturday, May 31, 2025 1:13:30 PM SGT
*/

public interface PlayerInterfaceOperations 
{

  // Authentication
  String login (String username, String password) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NoSuchUserFoundException;
  String adminLogin (String username, String password) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NoSuchUserFoundException;
  void logout (String userId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  String getUsernameByToken (String token) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;

  // Game Management
  String guess (String shownWord, int lobbyId, char guessChar, String userId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  void prepareNextRound (int lobbyId) throws Server.Exceptions.LostConnectionException;
  void declareWinner (int lobbyId, String username) throws Server.Exceptions.LostConnectionException;
  void returnToLobby (int lobbyId, String username) throws Server.Exceptions.LostConnectionException;
  String[] getReturnedPlayers (int lobbyId) throws Server.Exceptions.LostConnectionException;

  // For multi-round support
  boolean startNextRound (String userToken, int lobbyId) throws Server.Exceptions.NotLoggedInException, Server.Exceptions.LostConnectionException;
  String getLobbyHost (String userId, int lobbyId) throws Server.Exceptions.LostConnectionException;

  // Lobby Management
  int createLobby (String userId, String lobbyName) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  int joinLobby (String userId, int lobbyId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  void deleteLobby (String userId, int lobbyID) throws Server.Exceptions.LostConnectionException;
  void leaveLobby (String userId, int lobbyId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  int removeAllPlayersFromLobby (int lobbyID) throws Server.Exceptions.LostConnectionException;
  boolean removePlayerFromLobby (String userId, int lobbyId) throws Server.Exceptions.LostConnectionException;
  String[] getPlayersInLobby (String token, int lobbyId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  boolean startGame (String userToken, int lobbyId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  boolean isGameStarted (String userToken, int lobbyId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  boolean closeLobby (String userToken, int lobbyId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  int getWaitingDuration (String userToken, int lobbyId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;

  // Leaderboard
  String[] getLeaderboard (String userId) throws Server.Exceptions.LostConnectionException;
  String[] getLobbyList (String userId) throws Server.Exceptions.LostConnectionException;
} // interface PlayerInterfaceOperations
