package Server.PlayerSide;

/**
* Server/PlayerSide/PlayerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from playerinterface.idl
* Saturday, May 31, 2025 1:13:30 PM SGT
*/

public final class PlayerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.PlayerSide.PlayerInterface value = null;

  public PlayerInterfaceHolder ()
  {
  }

  public PlayerInterfaceHolder (Server.PlayerSide.PlayerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.PlayerSide.PlayerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.PlayerSide.PlayerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.PlayerSide.PlayerInterfaceHelper.type ();
  }

}
