package Server.CommonInterface;


/**
* Server/CommonInterface/_GameInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Friday, May 30, 2025 7:36:24 PM SGT
*/

public class _GameInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements Server.CommonInterface.GameInterface
{

  public Server.CommonObjects.GameRules getCurrentRules () throws Server.Exceptions.LostConnectionException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCurrentRules", true);
                $in = _invoke ($out);
                Server.CommonObjects.GameRules $result = Server.CommonObjects.GameRulesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:Server/Exceptions/LostConnectionException:1.0"))
                    throw Server.Exceptions.LostConnectionExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCurrentRules (        );
            } finally {
                _releaseReply ($in);
            }
  } // getCurrentRules

  public void applyGameRules (Server.CommonObjects.GameRules newRules) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.InvalidRulesException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("applyGameRules", true);
                Server.CommonObjects.GameRulesHelper.write ($out, newRules);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:Server/Exceptions/LostConnectionException:1.0"))
                    throw Server.Exceptions.LostConnectionExceptionHelper.read ($in);
                else if (_id.equals ("IDL:Server/Exceptions/NotLoggedInException:1.0"))
                    throw Server.Exceptions.NotLoggedInExceptionHelper.read ($in);
                else if (_id.equals ("IDL:Server/Exceptions/InvalidRulesException:1.0"))
                    throw Server.Exceptions.InvalidRulesExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                applyGameRules (newRules        );
            } finally {
                _releaseReply ($in);
            }
  } // applyGameRules

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Server/CommonInterface/GameInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "Server.CommonInterface._GameInterfaceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GameInterfaceStub
