package Server.CommonInterface;


/**
* Server/CommonInterface/CallBackInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public interface CallBackInterfaceOperations 
{

  // Game-related callbacks
  void updatePlayerList (String[] players);
  void gameStarted ();
  void wordToGuess (String wordWithBlanks);

  // e.g., "H _ N G M _ N"
  void guessResult (String playerId, boolean correct, char letter);
  void gameEnded (Server.CommonObjects.GameResult result);
} // interface CallBackInterfaceOperations
