package Server.CommonInterface;

/**
* Server/CommonInterface/CallBackInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public final class CallBackInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.CommonInterface.CallBackInterface value = null;

  public CallBackInterfaceHolder ()
  {
  }

  public CallBackInterfaceHolder (Server.CommonInterface.CallBackInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.CommonInterface.CallBackInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.CommonInterface.CallBackInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.CommonInterface.CallBackInterfaceHelper.type ();
  }

}
