package Server.CommonInterface;


/**
* Server/CommonInterface/CallBackInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

abstract public class CallBackInterfaceHelper
{
  private static String  _id = "IDL:Server/CommonInterface/CallBackInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, Server.CommonInterface.CallBackInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Server.CommonInterface.CallBackInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Server.CommonInterface.CallBackInterfaceHelper.id (), "CallBackInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Server.CommonInterface.CallBackInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CallBackInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Server.CommonInterface.CallBackInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Server.CommonInterface.CallBackInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server.CommonInterface.CallBackInterface)
      return (Server.CommonInterface.CallBackInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server.CommonInterface._CallBackInterfaceStub stub = new Server.CommonInterface._CallBackInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Server.CommonInterface.CallBackInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server.CommonInterface.CallBackInterface)
      return (Server.CommonInterface.CallBackInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server.CommonInterface._CallBackInterfaceStub stub = new Server.CommonInterface._CallBackInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
