package Server.CommonInterface;


/**
* Server/CommonInterface/CallBackInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public abstract class CallBackInterfacePOA extends org.omg.PortableServer.Servant
 implements CallBackInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("updatePlayerList", new Integer (0));
    _methods.put ("gameStarted", new Integer (1));
    _methods.put ("wordToGuess", new Integer (2));
    _methods.put ("guessResult", new Integer (3));
    _methods.put ("gameEnded", new Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Game-related callbacks
       case 0:  // Server/CommonInterface/CallBackInterface/updatePlayerList
       {
         String players[] = Server.CommonObjects.StringSequenceHelper.read (in);
         this.updatePlayerList (players);
         out = $rh.createReply();
         break;
       }

       case 1:  // Server/CommonInterface/CallBackInterface/gameStarted
       {
         this.gameStarted ();
         out = $rh.createReply();
         break;
       }

       case 2:  // Server/CommonInterface/CallBackInterface/wordToGuess
       {
         String wordWithBlanks = in.read_string ();
         this.wordToGuess (wordWithBlanks);
         out = $rh.createReply();
         break;
       }


  // e.g., "H _ N G M _ N"
       case 3:  // Server/CommonInterface/CallBackInterface/guessResult
       {
         String playerId = in.read_string ();
         boolean correct = in.read_boolean ();
         char letter = in.read_char ();
         this.guessResult (playerId, correct, letter);
         out = $rh.createReply();
         break;
       }

       case 4:  // Server/CommonInterface/CallBackInterface/gameEnded
       {
         Server.CommonObjects.GameResult result = Server.CommonObjects.GameResultHelper.read (in);
         this.gameEnded (result);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Server/CommonInterface/CallBackInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CallBackInterface _this() 
  {
    return CallBackInterfaceHelper.narrow(
    super._this_object());
  }

  public CallBackInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CallBackInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CallBackInterfacePOA
