package Server.CommonInterface;


/**
* Server/CommonInterface/CallBackInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public interface CallBackInterface extends CallBackInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CallBackInterface
