package Server.CommonInterface;


/**
* Server/CommonInterface/GameInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Friday, May 30, 2025 7:36:24 PM SGT
*/

public abstract class GameInterfacePOA extends org.omg.PortableServer.Servant
 implements Server.CommonInterface.GameInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCurrentRules", new java.lang.Integer (0));
    _methods.put ("applyGameRules", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Server/CommonInterface/GameInterface/getCurrentRules
       {
         try {
           Server.CommonObjects.GameRules $result = null;
           $result = this.getCurrentRules ();
           out = $rh.createReply();
           Server.CommonObjects.GameRulesHelper.write (out, $result);
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // Server/CommonInterface/GameInterface/applyGameRules
       {
         try {
           Server.CommonObjects.GameRules newRules = Server.CommonObjects.GameRulesHelper.read (in);
           this.applyGameRules (newRules);
           out = $rh.createReply();
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NotLoggedInExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.InvalidRulesException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.InvalidRulesExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Server/CommonInterface/GameInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameInterface _this() 
  {
    return GameInterfaceHelper.narrow(
    super._this_object());
  }

  public GameInterface _this(org.omg.CORBA.ORB orb) 
  {
    return GameInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class GameInterfacePOA
