package Server.CommonInterface;

/**
* Server/CommonInterface/GameInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Friday, May 30, 2025 7:36:24 PM SGT
*/

public final class GameInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.CommonInterface.GameInterface value = null;

  public GameInterfaceHolder ()
  {
  }

  public GameInterfaceHolder (Server.CommonInterface.GameInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.CommonInterface.GameInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.CommonInterface.GameInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.CommonInterface.GameInterfaceHelper.type ();
  }

}
