package Server.CommonInterface;


/**
* Server/CommonInterface/GameInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Friday, May 30, 2025 7:36:24 PM SGT
*/

public interface GameInterfaceOperations 
{
  Server.CommonObjects.GameRules getCurrentRules () throws Server.Exceptions.LostConnectionException;
  void applyGameRules (Server.CommonObjects.GameRules newRules) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.InvalidRulesException;
} // interface GameInterfaceOperations
