package Server.CommonObjects;

/**
* Server/CommonObjects/GameResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Friday, May 30, 2025 7:36:24 PM SGT
*/

public final class GameResultHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.CommonObjects.GameResult value = null;

  public GameResultHolder ()
  {
  }

  public GameResultHolder (Server.CommonObjects.GameResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.CommonObjects.GameResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.CommonObjects.GameResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.CommonObjects.GameResultHelper.type ();
  }

}
