package Server.CommonObjects;

/**
* Server/CommonObjects/GameRulesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public final class GameRulesHolder implements org.omg.CORBA.portable.Streamable
{
  public GameRules value = null;

  public GameRulesHolder ()
  {
  }

  public GameRulesHolder (GameRules initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameRulesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameRulesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameRulesHelper.type ();
  }

}
