package Server.CommonObjects;


/**
* Server/CommonObjects/GameRules.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Friday, May 30, 2025 7:36:24 PM SGT
*/

public final class GameRules implements org.omg.CORBA.portable.IDLEntity
{
  public int waitTime = (int)0;

  // Default 10s (join window)
  public int roundDuration = (int)0;

  // Default 30s (per round)
  public int maxGuesses = (int)0;

  // Default 5 (mistakes allowed)
  public int roundsToWin = (int)0;

  public GameRules ()
  {
  } // ctor

  public GameRules (int _waitTime, int _roundDuration, int _maxGuesses, int _roundsToWin)
  {
    waitTime = _waitTime;
    roundDuration = _roundDuration;
    maxGuesses = _maxGuesses;
    roundsToWin = _roundsToWin;
  } // ctor

} // class GameRules
