package Server.CommonObjects;


/**
* Server/CommonObjects/GameRules.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public final class GameRules implements org.omg.CORBA.portable.IDLEntity
{
  public int waitTime = (int)0;

  // Waiting time for players to join (default 10s)
  public int roundDuration = (int)0;

  // Duration for a game round (default 30s)
  public int maxGuesses = (int)0;

  // Maximum wrong guesses allowed per player (default 5)
  public int roundsToWin = (int)0;

  public GameRules ()
  {
  } // ctor

  public GameRules (int _waitTime, int _roundDuration, int _maxGuesses, int _roundsToWin)
  {
    waitTime = _waitTime;
    roundDuration = _roundDuration;
    maxGuesses = _maxGuesses;
    roundsToWin = _roundsToWin;
  } // ctor

} // class GameRules
