package Server.CommonObjects;

/**
* Server/CommonObjects/GameResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public final class GameResultHolder implements org.omg.CORBA.portable.Streamable
{
  public GameResult value = null;

  public GameResultHolder ()
  {
  }

  public GameResultHolder (GameResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameResultHelper.type ();
  }

}
