package Server.CommonObjects;

/**
* Server/CommonObjects/GameRulesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Friday, May 30, 2025 7:36:24 PM SGT
*/

public final class GameRulesHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.CommonObjects.GameRules value = null;

  public GameRulesHolder ()
  {
  }

  public GameRulesHolder (Server.CommonObjects.GameRules initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.CommonObjects.GameRulesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.CommonObjects.GameRulesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.CommonObjects.GameRulesHelper.type ();
  }

}
