package Server.CommonObjects;


/**
* Server/CommonObjects/LobbyInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public final class LobbyInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String lobbyId = null;
  public String hostName = null;
  public int currentPlayers = (int)0;
  public boolean gameStarted = false;

  public LobbyInfo ()
  {
  } // ctor

  public LobbyInfo (String _lobbyId, String _hostName, int _currentPlayers, boolean _gameStarted)
  {
    lobbyId = _lobbyId;
    hostName = _hostName;
    currentPlayers = _currentPlayers;
    gameStarted = _gameStarted;
  } // ctor

} // class LobbyInfo
