package Server.CommonObjects;

/**
* Server/CommonObjects/LobbyInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public final class LobbyInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public LobbyInfo value = null;

  public LobbyInfoHolder ()
  {
  }

  public LobbyInfoHolder (LobbyInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LobbyInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LobbyInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LobbyInfoHelper.type ();
  }

}
