package Server.CommonObjects;


/**
* Server/CommonObjects/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Monday, May 19, 2025 12:57:02 PM SGT
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String userId = null;
  public String displayName = null;
  public String password = null;

  public User ()
  {
  } // ctor

  public User (String _userId, String _displayName, String _password)
  {
    userId = _userId;
    displayName = _displayName;
    password = _password;
  } // ctor

} // class User
