package Server.CommonObjects;


/**
* Server/CommonObjects/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from commoninterface.idl
* Friday, May 30, 2025 7:36:24 PM SGT
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String displayName = null;
  public String password = null;

  public User ()
  {
  } // ctor

  public User (String _displayName, String _password)
  {
    displayName = _displayName;
    password = _password;
  } // ctor

} // class User
