package Server.Exceptions;

/**
* Server/Exceptions/AlreadyLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Monday, May 19, 2025 12:57:13 PM SGT
*/

public final class AlreadyLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.Exceptions.AlreadyLoggedInException value = null;

  public AlreadyLoggedInExceptionHolder ()
  {
  }

  public AlreadyLoggedInExceptionHolder (Server.Exceptions.AlreadyLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.Exceptions.AlreadyLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.Exceptions.AlreadyLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.Exceptions.AlreadyLoggedInExceptionHelper.type ();
  }

}
