package Server.Exceptions;

/**
* Server/Exceptions/InvalidRulesExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Friday, May 30, 2025 6:42:18 PM SGT
*/

public final class InvalidRulesExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.Exceptions.InvalidRulesException value = null;

  public InvalidRulesExceptionHolder ()
  {
  }

  public InvalidRulesExceptionHolder (Server.Exceptions.InvalidRulesException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.Exceptions.InvalidRulesExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.Exceptions.InvalidRulesExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.Exceptions.InvalidRulesExceptionHelper.type ();
  }

}
