package Server.Exceptions;


/**
* Server/Exceptions/InvalidRulesException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Friday, May 30, 2025 6:42:18 PM SGT
*/

public final class InvalidRulesException extends org.omg.CORBA.UserException
{
  public String message = null;

  public InvalidRulesException ()
  {
    super(InvalidRulesExceptionHelper.id());
  } // ctor

  public InvalidRulesException (String _message)
  {
    super(InvalidRulesExceptionHelper.id());
    message = _message;
  } // ctor


  public InvalidRulesException (String $reason, String _message)
  {
    super(InvalidRulesExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InvalidRulesException
