package Server.Exceptions;


/**
* Server/Exceptions/LostConnectionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Monday, May 19, 2025 12:57:13 PM SGT
*/


// General exceptions
public final class LostConnectionException extends org.omg.CORBA.UserException
{
  public String message = null;

  public LostConnectionException ()
  {
    super(LostConnectionExceptionHelper.id());
  } // ctor

  public LostConnectionException (String _message)
  {
    super(LostConnectionExceptionHelper.id());
    message = _message;
  } // ctor


  public LostConnectionException (String $reason, String _message)
  {
    super(LostConnectionExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class LostConnectionException
