package Server.Exceptions;

/**
* Server/Exceptions/LostConnectionExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Monday, May 19, 2025 12:57:13 PM SGT
*/


// General exceptions
public final class LostConnectionExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.Exceptions.LostConnectionException value = null;

  public LostConnectionExceptionHolder ()
  {
  }

  public LostConnectionExceptionHolder (Server.Exceptions.LostConnectionException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.Exceptions.LostConnectionExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.Exceptions.LostConnectionExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.Exceptions.LostConnectionExceptionHelper.type ();
  }

}
