package Server.Exceptions;


/**
* Server/Exceptions/NoSuchUserFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Monday, May 19, 2025 12:57:13 PM SGT
*/

public final class NoSuchUserFoundException extends org.omg.CORBA.UserException
{
  public String message = null;

  public NoSuchUserFoundException ()
  {
    super(NoSuchUserFoundExceptionHelper.id());
  } // ctor

  public NoSuchUserFoundException (String _message)
  {
    super(NoSuchUserFoundExceptionHelper.id());
    message = _message;
  } // ctor


  public NoSuchUserFoundException (String $reason, String _message)
  {
    super(NoSuchUserFoundExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NoSuchUserFoundException
