package Server.Exceptions;

/**
* Server/Exceptions/NoSuchUserFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Monday, May 19, 2025 12:57:13 PM SGT
*/

public final class NoSuchUserFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public NoSuchUserFoundException value = null;

  public NoSuchUserFoundExceptionHolder ()
  {
  }

  public NoSuchUserFoundExceptionHolder (NoSuchUserFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NoSuchUserFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NoSuchUserFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NoSuchUserFoundExceptionHelper.type ();
  }

}
