package Server.Exceptions;


/**
* Server/Exceptions/NotEnoughPlayersException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Friday, May 30, 2025 6:42:18 PM SGT
*/

public final class NotEnoughPlayersException extends org.omg.CORBA.UserException
{
  public String message = null;

  public NotEnoughPlayersException ()
  {
    super(NotEnoughPlayersExceptionHelper.id());
  } // ctor

  public NotEnoughPlayersException (String _message)
  {
    super(NotEnoughPlayersExceptionHelper.id());
    message = _message;
  } // ctor


  public NotEnoughPlayersException (String $reason, String _message)
  {
    super(NotEnoughPlayersExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NotEnoughPlayersException
