package Server.Exceptions;

/**
* Server/Exceptions/SessionNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Friday, May 30, 2025 6:42:18 PM SGT
*/

public final class SessionNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.Exceptions.SessionNotFoundException value = null;

  public SessionNotFoundExceptionHolder ()
  {
  }

  public SessionNotFoundExceptionHolder (Server.Exceptions.SessionNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.Exceptions.SessionNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.Exceptions.SessionNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.Exceptions.SessionNotFoundExceptionHelper.type ();
  }

}
