package Server.Exceptions;

/**
* Server/Exceptions/SessionNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Monday, May 19, 2025 12:57:13 PM SGT
*/

public final class SessionNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public SessionNotFoundException value = null;

  public SessionNotFoundExceptionHolder ()
  {
  }

  public SessionNotFoundExceptionHolder (SessionNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SessionNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SessionNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SessionNotFoundExceptionHelper.type ();
  }

}
