package Server.Exceptions;


/**
* Server/Exceptions/SessionFullException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Friday, May 30, 2025 6:42:18 PM SGT
*/


// Lobby exceptions
public final class SessionFullException extends org.omg.CORBA.UserException
{
  public String message = null;

  public SessionFullException ()
  {
    super(SessionFullExceptionHelper.id());
  } // ctor

  public SessionFullException (String _message)
  {
    super(SessionFullExceptionHelper.id());
    message = _message;
  } // ctor


  public SessionFullException (String $reason, String _message)
  {
    super(SessionFullExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class SessionFullException
