package Server.Exceptions;


/**
* Server/Exceptions/SessionNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Friday, May 30, 2025 6:42:18 PM SGT
*/

public final class SessionNotFoundException extends org.omg.CORBA.UserException
{
  public String message = null;

  public SessionNotFoundException ()
  {
    super(SessionNotFoundExceptionHelper.id());
  } // ctor

  public SessionNotFoundException (String _message)
  {
    super(SessionNotFoundExceptionHelper.id());
    message = _message;
  } // ctor


  public SessionNotFoundException (String $reason, String _message)
  {
    super(SessionNotFoundExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class SessionNotFoundException
