package Server.Exceptions;

/**
* Server/Exceptions/SessionFullExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Monday, May 19, 2025 12:57:13 PM SGT
*/


// Lobby exceptions
public final class SessionFullExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public SessionFullException value = null;

  public SessionFullExceptionHolder ()
  {
  }

  public SessionFullExceptionHolder (SessionFullException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SessionFullExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SessionFullExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SessionFullExceptionHelper.type ();
  }

}
