package Server.Exceptions;


/**
* Server/Exceptions/TimeoutException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Friday, May 30, 2025 6:42:18 PM SGT
*/

public final class TimeoutException extends org.omg.CORBA.UserException
{
  public String message = null;

  public TimeoutException ()
  {
    super(TimeoutExceptionHelper.id());
  } // ctor

  public TimeoutException (String _message)
  {
    super(TimeoutExceptionHelper.id());
    message = _message;
  } // ctor


  public TimeoutException (String $reason, String _message)
  {
    super(TimeoutExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class TimeoutException
