package Server.Exceptions;

/**
* Server/Exceptions/TimeoutExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Monday, May 19, 2025 12:57:13 PM SGT
*/

public final class TimeoutExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.Exceptions.TimeoutException value = null;

  public TimeoutExceptionHolder ()
  {
  }

  public TimeoutExceptionHolder (Server.Exceptions.TimeoutException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.Exceptions.TimeoutExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.Exceptions.TimeoutExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.Exceptions.TimeoutExceptionHelper.type ();
  }

}
