package Server.Exceptions;


/**
* Server/Exceptions/WrongGuessException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* Monday, May 19, 2025 12:57:13 PM SGT
*/


// Game exceptions
public final class WrongGuessException extends org.omg.CORBA.UserException
{
  public String message = null;

  public WrongGuessException ()
  {
    super(WrongGuessExceptionHelper.id());
  } // ctor

  public WrongGuessException (String _message)
  {
    super(WrongGuessExceptionHelper.id());
    message = _message;
  } // ctor


  public WrongGuessException (String $reason, String _message)
  {
    super(WrongGuessExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class WrongGuessException
